const LIBRARY_DATA = {
    school: {
        name: "Shree Saraswati Secondary School",
        library: "Shree Saraswati Secondary School Library",
        motto: "ज्ञान नै शक्ति हो — Knowledge is Power",
        address: "Changunarayan-08, Sudal, Bhaktapur, Nepal",
        phone: "01-5145000",
        email: "saraswatiss.2017@gmail.com",
        website: "saraswatibhss.edu.np",
        hours: {
            weekday: "१०:०० AM - ४:०० PM",
            saturday: "Closed",
            sunday: "१०:०० AM - ४:०० PM"
        }
    },

    categories: [
        { id: 1, name: "Nepali", icon: "book-open", color: "#ef4444", count: 12 },
        { id: 2, name: "English", icon: "languages", color: "#3b82f6", count: 12 },
        { id: 3, name: "Mathematics", icon: "calculator", color: "#f59e0b", count: 12 },
        { id: 4, name: "Science & Technology", icon: "atom", color: "#10b981", count: 10 },
        { id: 5, name: "Social Studies", icon: "globe", color: "#8b5cf6", count: 10 },
        { id: 6, name: "Health & Physical Education", icon: "heart", color: "#14b8a6", count: 6 },
        { id: 7, name: "Computer Science", icon: "cpu", color: "#06b6d4", count: 4 },
        { id: 8, name: "Economics", icon: "landmark", color: "#ec4899", count: 4 },
        { id: 9, name: "Natural Sciences", icon: "flask-conical", color: "#0ea5e9", count: 6 },
        { id: 10, name: "Business & Accountancy", icon: "briefcase", color: "#a855f7", count: 4 }
    ],

    books: [
        { id: 101, title: "Nepali Class 1", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "1", subject: "Nepali", language: "Nepali", pages: 56, year: 2076, description: "Official Nepali textbook for Grade 1 students as per National Curriculum Framework 2076. Develops foundational reading and writing skills in Nepali.", cover: "assets/covers/grade1-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 102, title: "English Class 1", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "1", subject: "English", language: "English", pages: 64, year: 2076, description: "Official English textbook for Grade 1 students aligned with the National Curriculum Framework 2076 of Nepal.", cover: "assets/covers/grade1-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 103, title: "Mathematics Class 1", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "1", subject: "Mathematics", language: "Nepali", pages: 52, year: 2076, description: "Mathematics textbook for Grade 1 covering basic numeracy, counting, shapes, and early problem-solving concepts.", cover: "assets/covers/grade1-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 104, title: "Social Studies Class 1", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "1", subject: "Social Studies", language: "Nepali", pages: 48, year: 2076, description: "Social Studies textbook for Grade 1 introducing family, neighbourhood, and community awareness.", cover: "assets/covers/grade1-science.svg", category: "Social Studies", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 105, title: "Health Class 1", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "1", subject: "Health", language: "Nepali", pages: 48, year: 2076, description: "Health textbook for Grade 1 covering personal hygiene, healthy habits, and safety awareness.", cover: "assets/covers/grade1-science.svg", category: "Health & Physical Education", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },

        { id: 106, title: "Nepali Class 2", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "2", subject: "Nepali", language: "Nepali", pages: 64, year: 2076, description: "Nepali language textbook for Grade 2 students developing reading comprehension, writing, and oral skills.", cover: "assets/covers/grade2-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 107, title: "English Class 2", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "2", subject: "English", language: "English", pages: 68, year: 2076, description: "English language textbook for Grade 2 with interactive activities, illustrations, and early literacy exercises.", cover: "assets/covers/grade2-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 108, title: "Mathematics Class 2", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "2", subject: "Mathematics", language: "Nepali", pages: 60, year: 2076, description: "Mathematics textbook for Grade 2 covering addition, subtraction, shapes, measurement, and number patterns.", cover: "assets/covers/grade2-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 109, title: "Social Studies Class 2", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "2", subject: "Social Studies", language: "Nepali", pages: 52, year: 2076, description: "Social Studies textbook for Grade 2 exploring my family, neighbourhood, and cultural diversity.", cover: "assets/covers/grade2-science.svg", category: "Social Studies", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 110, title: "Health Class 2", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "2", subject: "Health", language: "Nepali", pages: 48, year: 2076, description: "Health textbook for Grade 2 covering nutrition, cleanliness, personal hygiene, and basic safety.", cover: "assets/covers/grade2-science.svg", category: "Health & Physical Education", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },

        { id: 111, title: "Nepali Class 3", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "3", subject: "Nepali", language: "Nepali", pages: 72, year: 2077, description: "Nepali textbook for Grade 3 with prose, poetry, and grammar exercises to build language proficiency.", cover: "assets/covers/grade3-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 112, title: "English Class 3", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "3", subject: "English", language: "English", pages: 72, year: 2077, description: "English textbook for Grade 3 covering reading, writing, phonics, and basic grammar.", cover: "assets/covers/grade3-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 113, title: "Mathematics Class 3", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "3", subject: "Mathematics", language: "Nepali", pages: 68, year: 2077, description: "Mathematics textbook for Grade 3 covering multiplication, division, fractions, and basic geometry.", cover: "assets/covers/grade3-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 114, title: "My Social World Class 3", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "3", subject: "Social Studies", language: "Nepali", pages: 80, year: 2077, description: "Social Studies textbook introducing community, culture, festivals, and environment to Grade 3 students.", cover: "assets/covers/grade3-science.svg", category: "Social Studies", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 115, title: "Science Class 3", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "3", subject: "Science", language: "Nepali", pages: 76, year: 2077, description: "Basic science textbook for Grade 3 covering living things, materials, water, air, and the environment.", cover: "assets/covers/grade3-science.svg", category: "Science & Technology", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 116, title: "Health Class 3", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "3", subject: "Health", language: "Nepali", pages: 52, year: 2077, description: "Health and physical education textbook for Grade 3 covering hygiene, nutrition, and healthy living.", cover: "assets/covers/grade3-science.svg", category: "Health & Physical Education", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },

        { id: 117, title: "Nepali Class 4", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "4", subject: "Nepali", language: "Nepali", pages: 80, year: 2077, description: "Nepali textbook for Grade 4 with literature, grammar, composition, and creative writing sections.", cover: "assets/covers/grade4-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 118, title: "English Class 4", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "4", subject: "English", language: "English", pages: 80, year: 2077, description: "English textbook for Grade 4 covering reading comprehension, writing skills, grammar, and vocabulary.", cover: "assets/covers/grade4-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 119, title: "Mathematics Class 4", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "4", subject: "Mathematics", language: "Nepali", pages: 76, year: 2077, description: "Mathematics textbook for Grade 4 covering multi-digit operations, fractions, measurement, and geometry.", cover: "assets/covers/grade4-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 120, title: "Science Class 4", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "4", subject: "Science", language: "Nepali", pages: 84, year: 2077, description: "Science textbook for Grade 4 covering plants, animals, human body, matter, energy, and earth science.", cover: "assets/covers/grade4-science.svg", category: "Science & Technology", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 121, title: "Social Studies Class 4", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "4", subject: "Social Studies", language: "Nepali", pages: 72, year: 2077, description: "Social Studies textbook for Grade 4 covering Nepali history, geography, culture, and civic values.", cover: "assets/covers/grade4-science.svg", category: "Social Studies", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 122, title: "Health Population & Environment Class 4", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "4", subject: "Health", language: "Nepali", pages: 56, year: 2077, description: "Health, Population and Environment textbook for Grade 4 covering hygiene, population awareness, and environmental conservation.", cover: "assets/covers/grade4-science.svg", category: "Health & Physical Education", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },

        { id: 123, title: "Nepali Class 5", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "5", subject: "Nepali", language: "Nepali", pages: 96, year: 2078, description: "Advanced Nepali language textbook for Grade 5 with prose, poetry, grammar, and creative writing sections.", cover: "assets/covers/grade5-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.4, reviews: [] },
        { id: 124, title: "English Class 5", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "5", subject: "English", language: "English", pages: 104, year: 2078, description: "English textbook for Grade 5 covering reading comprehension, writing, grammar, literature, and communication.", pdfUrl: "assets/pdfs/grade5-english.pdf", cover: "assets/covers/grade5-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 125, title: "Mathematics Class 5", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "5", subject: "Mathematics", language: "Nepali", pages: 88, year: 2078, description: "Mathematics textbook covering fractions, decimals, geometry, data handling, and basic algebra for Grade 5.", cover: "assets/covers/grade5-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 126, title: "Science Class 5", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "5", subject: "Science", language: "Nepali", pages: 92, year: 2078, description: "Science textbook covering plants, animals, matter, energy, living things, and earth science for Grade 5.", cover: "assets/covers/grade5-science.svg", category: "Science & Technology", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 127, title: "Social Studies Class 5", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "5", subject: "Social Studies", language: "Nepali", pages: 80, year: 2078, description: "Social Studies textbook for Grade 5 covering history, geography, culture, and citizenship of Nepal.", cover: "assets/covers/grade5-science.svg", category: "Social Studies", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 128, title: "Health Population & Environment Class 5", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "5", subject: "Health", language: "Nepali", pages: 64, year: 2078, description: "Health, Population and Environment textbook for Grade 5 covering personal health, population studies, and environmental awareness.", cover: "assets/covers/grade5-science.svg", category: "Health & Physical Education", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },

        { id: 129, title: "Nepali Class 6", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "6", subject: "Nepali", language: "Nepali", pages: 108, year: 2078, description: "Nepali textbook for Grade 6 with comprehensive literature, grammar, composition, and reading comprehension.", cover: "assets/covers/grade6-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.4, reviews: [] },
        { id: 130, title: "English Class 6", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "6", subject: "English", language: "English", pages: 112, year: 2078, description: "English textbook for Grade 6 covering prose, poetry, grammar, composition, and language skills.", pdfUrl: "assets/pdfs/grade6-english.pdf", cover: "assets/covers/grade6-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 131, title: "Mathematics Class 6", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "6", subject: "Mathematics", language: "Nepali", pages: 100, year: 2078, description: "Mathematics textbook for Grade 6 covering integers, fractions, decimals, geometry, and data handling.", cover: "assets/covers/grade6-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 132, title: "Science Class 6", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "6", subject: "Science", language: "Nepali", pages: 104, year: 2078, description: "Science textbook for Grade 6 covering basic concepts in physics, chemistry, biology, and earth science.", cover: "assets/covers/grade6-science.svg", category: "Science & Technology", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 133, title: "Social Studies Class 6", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "6", subject: "Social Studies", language: "Nepali", pages: 96, year: 2078, description: "Social Studies textbook for Grade 6 covering history, geography, civics, and cultural heritage of Nepal.", cover: "assets/covers/grade6-social.svg", category: "Social Studies", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 134, title: "Health Population & Environment Class 6", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "6", subject: "Health", language: "Nepali", pages: 68, year: 2078, description: "Health, Population and Environment textbook for Grade 6 covering health awareness, population issues, and environment.", cover: "assets/covers/grade6-science.svg", category: "Health & Physical Education", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },

        { id: 137, title: "Nepali Class 7", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "7", subject: "Nepali", language: "Nepali", pages: 120, year: 2079, description: "Nepali textbook for Grade 7 with advanced literature, grammar, essay writing, and language analysis.", pdfUrl: "assets/pdfs/grade7-nepali.pdf", cover: "assets/covers/grade7-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.5, reviews: [] },
        { id: 138, title: "English Class 7", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "7", subject: "English", language: "English", pages: 120, year: 2079, description: "English textbook for Grade 7 covering literature, grammar, writing skills, and communication.", pdfUrl: "assets/pdfs/grade7-english.pdf", cover: "assets/covers/grade7-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 139, title: "Mathematics Class 7", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "7", subject: "Mathematics", language: "Nepali", pages: 116, year: 2079, description: "Mathematics textbook for Grade 7 covering algebra, geometry, statistics, ratio, and proportional reasoning.", pdfUrl: "assets/pdfs/grade7-math-nepali.pdf", cover: "assets/covers/grade7-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 140, title: "Science Class 7", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "7", subject: "Science", language: "Nepali", pages: 120, year: 2079, description: "Science textbook for Grade 7 covering physics, chemistry, biology, and environmental science concepts.", pdfUrl: "assets/pdfs/grade7-science-nepali.pdf", cover: "assets/covers/grade7-science.svg", category: "Science & Technology", totalCopies: 5, availableCopies: 5, rating: 4.4, reviews: [] },
        { id: 141, title: "Social Studies Class 7", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "7", subject: "Social Studies", language: "Nepali", pages: 108, year: 2079, description: "Social Studies textbook for Grade 7 covering Nepali history, geography, governance, and civic duties.", pdfUrl: "assets/pdfs/grade7-social.pdf", cover: "assets/covers/grade7-social.svg", category: "Social Studies", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 142, title: "Health Physical and Creative Arts Class 7", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "7", subject: "Health", language: "Nepali", pages: 76, year: 2079, description: "Health, Physical and Creative Arts textbook for Grade 7 covering health education, physical fitness, and creative expression.", cover: "assets/covers/grade7-health.svg", category: "Health & Physical Education", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },

        { id: 145, title: "Nepali Class 8", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "8", subject: "Nepali", language: "Nepali", pages: 128, year: 2079, description: "Comprehensive Nepali textbook for Grade 8 with literature, grammar, and creative writing as per updated curriculum 2078 BS.", pdfUrl: "assets/pdfs/grade8-nepali.pdf", cover: "assets/covers/grade8-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.5, reviews: [] },
        { id: 146, title: "English Class 8", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "8", subject: "English", language: "English", pages: 136, year: 2079, description: "English language and literature textbook for Grade 8 covering prose, poetry, drama, grammar, and composition.", pdfUrl: "assets/pdfs/grade8-english.pdf", cover: "assets/covers/grade8-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 147, title: "Mathematics Class 8", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "8", subject: "Mathematics", language: "Nepali", pages: 144, year: 2079, description: "Mathematics textbook for Grade 8 covering algebra, geometry, statistics, mensuration, and commercial mathematics.", pdfUrl: "assets/pdfs/grade8-math-nepali.pdf", cover: "assets/covers/grade8-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 148, title: "Science & Technology Class 8", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "8", subject: "Science & Technology", language: "Nepali", pages: 152, year: 2079, description: "Science & Technology textbook for Grade 8 covering physics, chemistry, biology, and technology concepts.", pdfUrl: "assets/pdfs/grade8-science-nepali.pdf", cover: "assets/covers/grade8-science.svg", category: "Science & Technology", totalCopies: 5, availableCopies: 5, rating: 4.4, reviews: [] },
        { id: 149, title: "Social Studies Class 8", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "8", subject: "Social Studies", language: "Nepali", pages: 120, year: 2079, description: "Social Studies textbook for Grade 8 covering history, geography, civics, and economics of Nepal.", pdfUrl: "assets/pdfs/grade8-social.pdf", cover: "assets/covers/grade8-social.svg", category: "Social Studies", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 150, title: "Health Physical and Creative Arts Class 8", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "8", subject: "Health", language: "Nepali", pages: 96, year: 2079, description: "Health, Physical and Creative Arts textbook for Grade 8 covering physical fitness, health, and creative expression.", cover: "assets/covers/grade8-health.svg", category: "Health & Physical Education", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },

        { id: 152, title: "Nepali Class 9", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "9", subject: "Nepali", language: "Nepali", pages: 140, year: 2080, description: "Advanced Nepali textbook for Grade 9 with comprehensive literature, grammar, and language analysis.", pdfUrl: "assets/pdfs/grade9-nepali.pdf", cover: "assets/covers/grade9-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.5, reviews: [] },
        { id: 153, title: "English Class 9", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "9", subject: "English", language: "English", pages: 148, year: 2080, description: "English textbook for Grade 9 covering literature, grammar, writing skills, reading comprehension, and communication.", pdfUrl: "assets/pdfs/grade9-english.pdf", cover: "assets/covers/grade9-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 154, title: "Compulsory Mathematics Class 9", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "9", subject: "Mathematics", language: "Nepali", pages: 160, year: 2080, description: "Compulsory Mathematics textbook for Grade 9 covering algebra, geometry, statistics, and mensuration.", pdfUrl: "assets/pdfs/grade9-math-nepali.pdf", cover: "assets/covers/grade9-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 155, title: "Optional Mathematics Class 9", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "9", subject: "Mathematics", language: "English", pages: 156, year: 2080, description: "Optional Mathematics textbook for Grade 9 covering advanced algebra, trigonometry, and coordinate geometry.", pdfUrl: "assets/pdfs/grade9-optmath-english.pdf", cover: "assets/covers/grade9-optmath.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 156, title: "Science & Technology Class 9", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "9", subject: "Science & Technology", language: "Nepali", pages: 168, year: 2080, description: "Science & Technology textbook for Grade 9 covering physics, chemistry, biology, and astronomy.", pdfUrl: "assets/pdfs/grade9-science-nepali.pdf", cover: "assets/covers/grade9-science.svg", category: "Science & Technology", totalCopies: 5, availableCopies: 5, rating: 4.5, reviews: [] },
        { id: 157, title: "Social Studies Class 9", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "9", subject: "Social Studies", language: "Nepali", pages: 132, year: 2080, description: "Social Studies textbook for Grade 9 covering Nepali history, geography, population studies, and civic responsibility.", pdfUrl: "assets/pdfs/grade9-social.pdf", cover: "assets/covers/grade9-social.svg", category: "Social Studies", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 158, title: "Computer Science Class 9", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "9", subject: "Computer Science", language: "English", pages: 128, year: 2080, description: "Computer Science textbook for Grade 9 covering programming basics, digital literacy, hardware, and ICT.", pdfUrl: "assets/pdfs/grade9-computer-english.pdf", cover: "assets/covers/grade9-computer.svg", category: "Computer Science", totalCopies: 5, availableCopies: 5, rating: 4.4, reviews: [] },

        { id: 160, title: "Nepali Class 10", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "10", subject: "Nepali", language: "Nepali", pages: 156, year: 2081, description: "Advanced Nepali literature and language textbook for Grade 10 SEE preparation covering prose, poetry, and grammar.", pdfUrl: "assets/pdfs/grade10-nepali.pdf", cover: "assets/covers/grade10-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.6, reviews: [] },
        { id: 161, title: "English Class 10", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "10", subject: "English", language: "English", pages: 164, year: 2081, description: "English textbook for Grade 10 SEE preparation covering literature, grammar, writing, and reading comprehension.", pdfUrl: "assets/pdfs/grade10-english.pdf", cover: "assets/covers/grade10-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.4, reviews: [] },
        { id: 162, title: "Compulsory Mathematics Class 10", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "10", subject: "Mathematics", language: "Nepali", pages: 172, year: 2081, description: "Compulsory Mathematics textbook for Grade 10 SEE preparation covering algebra, geometry, statistics, and mensuration.", pdfUrl: "assets/pdfs/grade10-math-nepali.pdf", cover: "assets/covers/grade10-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 163, title: "Optional Mathematics Class 10", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "10", subject: "Mathematics", language: "English", pages: 168, year: 2081, description: "Optional Mathematics textbook for Grade 10 covering advanced topics including calculus introduction and probability.", pdfUrl: "assets/pdfs/grade10-optmath-english.pdf", cover: "assets/covers/grade10-optmath.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.4, reviews: [] },
        { id: 164, title: "Science & Technology Class 10", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "10", subject: "Science & Technology", language: "Nepali", pages: 180, year: 2081, description: "Science & Technology textbook for Grade 10 SEE preparation covering physics, chemistry, biology, and astronomy.", pdfUrl: "assets/pdfs/grade10-science-nepali.pdf", cover: "assets/covers/grade10-science.svg", category: "Science & Technology", totalCopies: 5, availableCopies: 5, rating: 4.5, reviews: [] },
        { id: 165, title: "Social Studies Class 10", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "10", subject: "Social Studies", language: "Nepali", pages: 144, year: 2081, description: "Social Studies textbook for Grade 10 SEE preparation covering history, geography, civics, and economics of Nepal.", pdfUrl: "assets/pdfs/grade10-social.pdf", cover: "assets/covers/grade10-social.svg", category: "Social Studies", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 166, title: "Computer Science Class 10", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "10", subject: "Computer Science", language: "English", pages: 136, year: 2081, description: "Computer Science textbook for Grade 10 covering programming, web development, databases, and networking.", pdfUrl: "assets/pdfs/grade10-computer-english.pdf", cover: "assets/covers/grade10-computer.svg", category: "Computer Science", totalCopies: 5, availableCopies: 5, rating: 4.5, reviews: [] },
        { id: 167, title: "Health Population & Environment Class 10", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "10", subject: "Health", language: "Nepali", pages: 108, year: 2081, description: "Health, Population and Environment textbook for Grade 10 SEE preparation covering health, demographics, and ecology.", cover: "assets/covers/grade10-science.svg", category: "Health & Physical Education", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },

        { id: 170, title: "Nepali Class 11", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "11", subject: "Nepali", language: "Nepali", pages: 160, year: 2081, description: "Nepali textbook for Grade 11 covering literature, language, and creative writing as per the higher secondary curriculum.", pdfUrl: "assets/pdfs/grade11-nepali.pdf", cover: "assets/covers/grade10-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 171, title: "English Class 11", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "11", subject: "English", language: "English", pages: 168, year: 2081, description: "English textbook for Grade 11 covering literature, language skills, critical thinking, and academic writing.", pdfUrl: "assets/pdfs/grade11-english.pdf", cover: "assets/covers/grade10-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 172, title: "Mathematics Class 11", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "11", subject: "Mathematics", language: "English", pages: 180, year: 2081, description: "Mathematics textbook for Grade 11 covering algebra, trigonometry, coordinate geometry, and calculus.", cover: "assets/covers/grade10-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 173, title: "Physics Class 11", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "11", subject: "Physics", language: "English", pages: 192, year: 2081, description: "Physics textbook for Grade 11 covering mechanics, thermodynamics, waves, optics, and electricity.", pdfUrl: "assets/pdfs/grade11-physics.pdf", cover: "assets/covers/grade10-science.svg", category: "Natural Sciences", totalCopies: 5, availableCopies: 5, rating: 4.4, reviews: [] },
        { id: 174, title: "Chemistry Class 11", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "11", subject: "Chemistry", language: "English", pages: 184, year: 2081, description: "Chemistry textbook for Grade 11 covering atomic structure, chemical bonding, reactions, and periodic table.", pdfUrl: "assets/pdfs/grade11-chemistry.pdf", cover: "assets/covers/grade10-science.svg", category: "Natural Sciences", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 175, title: "Biology Class 11", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "11", subject: "Biology", language: "English", pages: 196, year: 2081, description: "Biology textbook for Grade 11 covering cell biology, genetics, evolution, ecology, and human biology.", pdfUrl: "assets/pdfs/grade11-biology.pdf", cover: "assets/covers/grade10-science.svg", category: "Natural Sciences", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 176, title: "Computer Science Class 11", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "11", subject: "Computer Science", language: "English", pages: 148, year: 2081, description: "Computer Science textbook for Grade 11 covering programming, data structures, algorithms, and computer architecture.", cover: "assets/covers/grade10-computer.svg", category: "Computer Science", totalCopies: 5, availableCopies: 5, rating: 4.4, reviews: [] },
        { id: 177, title: "Economics Class 11", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "11", subject: "Economics", language: "English", pages: 140, year: 2081, description: "Economics textbook for Grade 11 covering microeconomics, macroeconomics, demand and supply, and market structures.", cover: "assets/covers/grade10-social.svg", category: "Economics", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 178, title: "Accountancy Class 11", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "11", subject: "Accountancy", language: "English", pages: 156, year: 2081, description: "Accountancy textbook for Grade 11 covering financial accounting, partnership accounts, and introduction to company accounts.", cover: "assets/covers/grade10-math.svg", category: "Business & Accountancy", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 179, title: "Business Studies Class 11", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "11", subject: "Business Studies", language: "English", pages: 144, year: 2081, description: "Business Studies textbook for Grade 11 covering business organisation, management, marketing, and entrepreneurship.", cover: "assets/covers/grade10-social.svg", category: "Business & Accountancy", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },

        { id: 180, title: "Nepali Class 12", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "12", subject: "Nepali", language: "Nepali", pages: 172, year: 2082, description: "Nepali textbook for Grade 12 covering advanced literature, linguistics, research methodology, and critical analysis.", pdfUrl: "assets/pdfs/grade12-nepali.pdf", cover: "assets/covers/grade10-nepali.svg", category: "Nepali", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 181, title: "English Class 12", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "12", subject: "English", language: "English", pages: 176, year: 2082, description: "English textbook for Grade 12 covering advanced literature, critical analysis, academic writing, and linguistics.", pdfUrl: "assets/pdfs/grade12-english.pdf", cover: "assets/covers/grade10-english.svg", category: "English", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 182, title: "Mathematics Class 12", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "12", subject: "Mathematics", language: "English", pages: 200, year: 2082, description: "Mathematics textbook for Grade 12 covering advanced calculus, linear algebra, probability, and differential equations.", cover: "assets/covers/grade10-math.svg", category: "Mathematics", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 183, title: "Physics Class 12", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "12", subject: "Physics", language: "English", pages: 196, year: 2082, description: "Physics textbook for Grade 12 covering electricity and magnetism, modern physics, nuclear physics, and electronics.", pdfUrl: "assets/pdfs/grade12-physics.pdf", cover: "assets/covers/grade10-science.svg", category: "Natural Sciences", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 184, title: "Chemistry Class 12", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "12", subject: "Chemistry", language: "English", pages: 192, year: 2082, description: "Chemistry textbook for Grade 12 covering organic chemistry, inorganic chemistry, physical chemistry, and applied chemistry.", pdfUrl: "assets/pdfs/grade12-chemistry.pdf", cover: "assets/covers/grade10-science.svg", category: "Natural Sciences", totalCopies: 5, availableCopies: 5, rating: 4.2, reviews: [] },
        { id: 185, title: "Biology Class 12", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "12", subject: "Biology", language: "English", pages: 200, year: 2082, description: "Biology textbook for Grade 12 covering molecular biology, biotechnology, biodiversity, and environmental biology.", pdfUrl: "assets/pdfs/grade12-biology.pdf", cover: "assets/covers/grade10-science.svg", category: "Natural Sciences", totalCopies: 5, availableCopies: 5, rating: 4.3, reviews: [] },
        { id: 186, title: "Computer Science Class 12", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "12", subject: "Computer Science", language: "English", pages: 160, year: 2082, description: "Computer Science textbook for Grade 12 covering advanced programming, database systems, networking, and software engineering.", cover: "assets/covers/grade10-computer.svg", category: "Computer Science", totalCopies: 5, availableCopies: 5, rating: 4.4, reviews: [] },
        { id: 187, title: "Economics Class 12", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "12", subject: "Economics", language: "English", pages: 152, year: 2082, description: "Economics textbook for Grade 12 covering advanced microeconomics, macroeconomics, development economics, and Nepali economic policy.", cover: "assets/covers/grade10-social.svg", category: "Economics", totalCopies: 5, availableCopies: 5, rating: 4.1, reviews: [] },
        { id: 188, title: "Accountancy Class 12", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "12", subject: "Accountancy", language: "English", pages: 168, year: 2082, description: "Accountancy textbook for Grade 12 covering company accounts, financial statements, analysis, and cost accounting.", cover: "assets/covers/grade10-math.svg", category: "Business & Accountancy", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] },
        { id: 189, title: "Business Studies Class 12", author: "CDC Nepal", publisher: "CDC, MoEST", grade: "12", subject: "Business Studies", language: "English", pages: 156, year: 2082, description: "Business Studies textbook for Grade 12 covering advanced management, international business, finance, and strategic planning.", cover: "assets/covers/grade10-social.svg", category: "Business & Accountancy", totalCopies: 5, availableCopies: 5, rating: 4.0, reviews: [] }
    ],

    students: [],

    teachers: [],

    borrowedBooks: [],

    reservations: [],

    notifications: [
        { id: 1, type: "new_book", title: "New Arrivals", message: "CDC textbooks for the academic session 2083 have been added to the digital library.", time: "1 day ago", read: true, icon: "book-plus" },
        { id: 2, type: "event", title: "Book Fair 2083", message: "Annual book fair starts next Monday. Don't miss it!", time: "2 days ago", read: true, icon: "calendar" }
    ],

    announcements: [
        { id: 1, title: "CDC Textbook Distribution", content: "New CDC textbooks for the academic session 2083 have arrived. Collect from the library counter.", date: "2026-07-15", priority: "high" },
        { id: 2, title: "Digital Library Access", content: "Access CDC textbooks online through our digital library. Grades 5-12 PDFs now available.", date: "2026-07-10", priority: "medium" },
        { id: 3, title: "Library Hours Update", content: "Starting Shrawan, the library will open at 10:00 AM on weekdays.", date: "2026-07-08", priority: "low" },
        { id: 4, title: "Book Donation Drive", content: "Donate your gently used books to our library collection. All donors receive a thank-you card.", date: "2026-07-05", priority: "medium" }
    ],

    events: [
        { id: 1, title: "Annual Book Fair", description: "Explore CDC textbooks and reference books from various publishers.", date: "2026-07-21", time: "9:00 AM - 4:00 PM", location: "Main Hall", type: "book-fair" },
        { id: 2, title: "Creative Writing Workshop", description: "Learn Nepali and English creative writing from published authors.", date: "2026-07-25", time: "2:00 PM - 5:00 PM", location: "Library Hall B", type: "workshop" },
        { id: 3, title: "SEE Preparation Seminar", description: "Expert tips for SEE preparation in Science, Math, and English.", date: "2026-08-01", time: "10:00 AM - 1:00 PM", location: "Auditorium", type: "competition" },
        { id: 4, title: "Reading Competition", description: "Inter-school reading competition in Nepali and English.", date: "2026-08-05", time: "3:00 PM - 5:00 PM", location: "Library Lobby", type: "meet-greet" }
    ],

    quotes: [
        { text: "पुस्तक भनेको बुद्धिको खानी हो।", author: "नेपाली उखान" },
        { text: "A reader lives a thousand lives before he dies. The man who never reads lives only one.", author: "George R.R. Martin" },
        { text: "ज्ञान नै शक्ति हो।", author: "नेपाली उखान" },
        { text: "Books are a uniquely portable magic.", author: "Stephen King" },
        { text: "पढ्ने मान्छे सधैं अगाडि हुन्छ।", author: "नेपाली उखान" }
    ],

    rules: [
        { title: "Digital Access Only", description: "All textbooks are available digitally through the library portal. No physical copies are distributed through this system." },
        { title: "Personal Use Only", description: "E-books and digital resources are for personal educational use only. Redistribution is prohibited." },
        { title: "Fair Use Policy", description: "Download materials only as needed. Avoid unnecessary bulk downloads to conserve server bandwidth." },
        { title: "Academic Integrity", description: "Use CDC textbooks as study aids. Always cite sources in academic work." },
        { title: "Silence Zone", description: "Maintain silence in reading areas. Group discussions are allowed in designated areas only." },
        { title: "No Unauthorized Distribution", description: "Do not share login credentials or redistribute downloaded materials to unauthorized persons." },
        { title: "Report Issues", description: "Report broken links, missing files, or other issues to the librarian immediately." },
        { title: "Respect the Resource", description: "Handle library equipment and facilities with care. Report any damage promptly." }
    ],

    readingStreaks: [],

    achievements: [],

    digitalBooks: [
        { id: 1, title: "Nepali (नेपाली) — Class 7", author: "CDC Nepal", type: "pdf", category: "Grade 7", pages: 120, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/7.Reduced-class%207%20Nepali%20final_lnxtmxf.pdf", featured: true },
        { id: 2, title: "English — Class 7", author: "CDC Nepal", type: "pdf", category: "Grade 7", pages: 120, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/6.%20Reduced-class%207%20English%20final_lro4mmc.pdf" },
        { id: 3, title: "Mathematics (नेपाली) — Class 7", author: "CDC Nepal", type: "pdf", category: "Grade 7", pages: 116, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/0007_MathsGrade7NepaliEdition_gtyci7i.pdf" },
        { id: 4, title: "Mathematics (English) — Class 7", author: "CDC Nepal", type: "pdf", category: "Grade 7", pages: 116, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/0007_MathematicsGrade7EnglishTranslation_fqz5dkt.pdf" },
        { id: 5, title: "Science & Technology (नेपाली) — Class 7", author: "CDC Nepal", type: "pdf", category: "Grade 7", pages: 120, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/9.Reduced-class%207%20science%20final_ypdi9pg.pdf" },
        { id: 6, title: "Science & Technology (English) — Class 7", author: "CDC Nepal", type: "pdf", category: "Grade 7", pages: 120, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Science%20and%20Technology%20Grade%207%28English%20Translation%29%20Reduced_yvhc6cc.pdf" },
        { id: 7, title: "Social Studies & Human Value Education — Class 7", author: "CDC Nepal", type: "pdf", category: "Grade 7", pages: 108, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/8.Reduced-class%207%20samajik%20Final_zq04sfi.pdf" },
        { id: 8, title: "Health, Physical & Creative Arts (नेपाली) — Class 7", author: "CDC Nepal", type: "pdf", category: "Grade 7", pages: 76, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/1.%20class%207%20health%20final-compressed_pqmbsce.pdf" },

        { id: 9, title: "Nepali (नेपाली) — Class 8", author: "CDC Nepal", type: "pdf", category: "Grade 8", pages: 128, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/2.%20Reduced-class%208%20nepali%20final_ahsi1f6.pdf", featured: true },
        { id: 10, title: "English — Class 8", author: "CDC Nepal", type: "pdf", category: "Grade 8", pages: 136, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/1.%20Reduced-class%208%20English%20final_vfiq0xm.pdf" },
        { id: 11, title: "Mathematics (नेपाली) — Class 8", author: "CDC Nepal", type: "pdf", category: "Grade 8", pages: 144, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/%E0%A4%97%E0%A4%A3%E0%A4%BF%E0%A4%A4%20%E0%A4%95%E0%A4%95%E0%A5%8D%E0%A4%B7%E0%A4%BE%20-%20%E0%A5%A8%20%28%E0%A4%A8%E0%A5%87%E0%A4%AA%E0%A4%BE%E0%A4%B2%E0%A5%80%20%E0%A4%B8%E0%A4%82%E0%A4%B8%E0%A5%8D%E0%A4%95%E0%A4%B0%E0%A4%A3%29_zwpacgp.pdf" },
        { id: 12, title: "Science & Environment (नेपाली) — Class 8", author: "CDC Nepal", type: "pdf", category: "Grade 8", pages: 152, pdfUrl: "https://moecdc.gov.np/storage/gallery/1684481476.pdf" },
        { id: 13, title: "Social Studies & Population Education — Class 8", author: "CDC Nepal", type: "pdf", category: "Grade 8", pages: 120, pdfUrl: "https://moecdc.gov.np/storage/gallery/1682060895.pdf" },
        { id: 14, title: "Health, Physical & Creative Arts (नेपाली) — Class 8", author: "CDC Nepal", type: "pdf", category: "Grade 8", pages: 96, pdfUrl: "https://moecdc.gov.np/storage/gallery/1708859361.pdf" },

        { id: 15, title: "Nepali (नेपाली) — Class 9", author: "CDC Nepal", type: "pdf", category: "Grade 9", pages: 140, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Class9_NepaliReduced_vkvqar.pdf", featured: true },
        { id: 16, title: "English — Class 9", author: "CDC Nepal", type: "pdf", category: "Grade 9", pages: 148, pdfUrl: "https://moecdc.gov.np/storage/gallery/1688289325.pdf" },
        { id: 17, title: "Mathematics (नेपाली) — Class 9", author: "CDC Nepal", type: "pdf", category: "Grade 9", pages: 160, pdfUrl: "https://moecdc.gov.np/storage/gallery/1672910414.pdf" },
        { id: 18, title: "Mathematics (English) — Class 9", author: "CDC Nepal", type: "pdf", category: "Grade 9", pages: 160, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/0009_MathematicsGrade9EnglishTranslation_fqz5dkt.pdf" },
        { id: 19, title: "Science & Technology (नेपाली) — Class 9", author: "CDC Nepal", type: "pdf", category: "Grade 9", pages: 168, pdfUrl: "https://moecdc.gov.np/storage/gallery/1672910467.pdf" },
        { id: 20, title: "Science & Technology (English) — Class 9", author: "CDC Nepal", type: "pdf", category: "Grade 9", pages: 168, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Science%20and%20Technology%20Grade%209%28English%20Translation%29 Reduced_lro4mmc.pdf" },
        { id: 21, title: "Social Studies (नेपाली) — Class 9", author: "CDC Nepal", type: "pdf", category: "Grade 9", pages: 132, pdfUrl: "https://moecdc.gov.np/storage/gallery/1672910576.pdf" },
        { id: 22, title: "Optional Mathematics (English) — Class 9", author: "CDC Nepal", type: "pdf", category: "Grade 9", pages: 156, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Final%20opt%20math%20eng%20for%20press%209%20%282082-11-26%29%201-12%20PM%20%281%29_1iwtizb.pdf" },
        { id: 23, title: "Computer Science (English) — Class 9", author: "CDC Nepal", type: "pdf", category: "Grade 9", pages: 128, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Computer%20Science%20Grade%209_r12pxcl.pdf" },

        { id: 24, title: "Nepali (नेपाली) — Class 10", author: "CDC Nepal", type: "pdf", category: "Grade 10", pages: 156, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/class%2010%20Nepali%20Final_kjvwvtg.pdf", featured: true },
        { id: 25, title: "English — Class 10", author: "CDC Nepal", type: "pdf", category: "Grade 10", pages: 164, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/9.Reduced-class%2010%20English%20Final_hsjc8bm.pdf" },
        { id: 26, title: "Compulsory Mathematics (नेपाली) — Class 10", author: "CDC Nepal", type: "pdf", category: "Grade 10", pages: 172, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/%E0%A4%97%E0%A4%A3%E0%A4%BF%E0%A4%A4%20%E0%A4%95%E0%A4%95%E0%A5%8D%E0%A4%B7%E0%A4%BE%20-%20%E0%A5%A7%E0%A5%A6_ncrmipa.pdf" },
        { id: 27, title: "Science & Technology (नेपाली) — Class 10", author: "CDC Nepal", type: "pdf", category: "Grade 10", pages: 180, pdfUrl: "https://moecdc.gov.np/storage/gallery/1682668847.pdf" },
        { id: 28, title: "Social Studies (नेपाली) — Class 10", author: "CDC Nepal", type: "pdf", category: "Grade 10", pages: 144, pdfUrl: "https://moecdc.gov.np/storage/gallery/1710845068.pdf" },
        { id: 29, title: "Optional Mathematics (English) — Class 10", author: "CDC Nepal", type: "pdf", category: "Grade 10", pages: 168, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Final%20opt%20math%20eng%20for%20press%2010%20%282082-11-26%29%201-12%20PM.pdf" },
        { id: 30, title: "Computer Science (English) — Class 10", author: "CDC Nepal", type: "pdf", category: "Grade 10", pages: 136, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Computer%20Science%20Grade%2010_bx2mpl.pdf" },

        { id: 31, title: "Nepali — Class 11", author: "CDC Nepal", type: "pdf", category: "Grade 11", pages: 160, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-nepali11.pdf" },
        { id: 32, title: "English — Class 11", author: "CDC Nepal", type: "pdf", category: "Grade 11", pages: 168, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-english11.pdf" },
        { id: 33, title: "Physics — Class 11", author: "CDC Nepal", type: "pdf", category: "Grade 11", pages: 192, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-physics11.pdf" },
        { id: 34, title: "Chemistry — Class 11", author: "CDC Nepal", type: "pdf", category: "Grade 11", pages: 184, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-chemistry11.pdf" },
        { id: 35, title: "Biology — Class 11", author: "CDC Nepal", type: "pdf", category: "Grade 11", pages: 196, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-biology11.pdf" },
        { id: 36, title: "Social Studies (नेपाली) — Class 11", author: "CDC Nepal", type: "pdf", category: "Grade 11", pages: 192, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-social%2011_0yfbndw.pdf" },

        { id: 37, title: "Nepali — Class 12", author: "CDC Nepal", type: "pdf", category: "Grade 12", pages: 172, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-%20nepali12%20four%20colour_uhkgair.pdf" },
        { id: 38, title: "English — Class 12", author: "CDC Nepal", type: "pdf", category: "Grade 12", pages: 176, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-english12.pdf" },
        { id: 39, title: "Physics — Class 12", author: "CDC Nepal", type: "pdf", category: "Grade 12", pages: 196, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-physics12.pdf" },
        { id: 40, title: "Chemistry — Class 12", author: "CDC Nepal", type: "pdf", category: "Grade 12", pages: 192, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-chemistry12.pdf" },
        { id: 41, title: "Biology — Class 12", author: "CDC Nepal", type: "pdf", category: "Grade 12", pages: 200, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-biology12.pdf" },
        { id: 42, title: "Social Studies (नेपाली) — Class 12", author: "CDC Nepal", type: "pdf", category: "Grade 12", pages: 144, pdfUrl: "https://giwmscdnone.gov.np/media/pdf_upload/Reds-social12%20for%20web_wis1pow.pdf" },

        { id: 43, title: "Nepali — Class 5", author: "CDC Nepal", type: "pdf", category: "Grade 5", pages: 96, pdfUrl: "https://moecdc.gov.np/storage/gallery/1681211870.pdf" },
        { id: 44, title: "English — Class 5", author: "CDC Nepal", type: "pdf", category: "Grade 5", pages: 104, pdfUrl: "https://moecdc.gov.np/storage/gallery/1681367111.pdf" },
        { id: 45, title: "Mathematics (नेपाली) — Class 5", author: "CDC Nepal", type: "pdf", category: "Grade 5", pages: 88, pdfUrl: "https://moecdc.gov.np/storage/gallery/1681211690.pdf" },
        { id: 46, title: "Nepali — Class 6", author: "CDC Nepal", type: "pdf", category: "Grade 6", pages: 108, pdfUrl: "https://moecdc.gov.np/storage/gallery/1672799748.pdf" },
        { id: 47, title: "English — Class 6", author: "CDC Nepal", type: "pdf", category: "Grade 6", pages: 112, pdfUrl: "https://moecdc.gov.np/storage/gallery/1672799804.pdf" },
        { id: 48, title: "Mathematics (नेपाली) — Class 6", author: "CDC Nepal", type: "pdf", category: "Grade 6", pages: 100, pdfUrl: "https://moecdc.gov.np/storage/gallery/1672799879.pdf" }
    ],

    stats: {
        totalBooks: 89,
        availableBooks: 89,
        borrowedBooks: 0,
        reservedBooks: 0,
        totalStudents: 0,
        totalTeachers: 0,
        visitorsToday: 0,
        todayBorrowing: 0,
        weeklyBorrowing: 0,
        monthlyBorrowing: 0,
        booksReturned: 0,
        lateReturns: 0,
        fineCollected: 0
    },

    monthlyStats: [],

    studyMaterials: [
        { id: 1, title: "SEE Compulsory Mathematics Question Paper 2081", type: "question-paper", grade: "10", subject: "Compulsory Mathematics", year: "2081", examType: "SEE", description: "Previous year SEE Compulsory Mathematics question paper (Nepali medium).", uploadedBy: "Laxmi Devi", uploadedAt: "2026-07-10", downloads: 0 },
        { id: 2, title: "SEE Compulsory English Question Paper 2081", type: "question-paper", grade: "10", subject: "Compulsory English", year: "2081", examType: "SEE", description: "Previous year SEE Compulsory English question paper.", uploadedBy: "Laxmi Devi", uploadedAt: "2026-07-10", downloads: 0 },
        { id: 3, title: "BLE Mathematics Question Paper 2081", type: "question-paper", grade: "8", subject: "Mathematics", year: "2081", examType: "BLE", description: "Basic Level Examination (Grade 8) Mathematics question paper 2081.", uploadedBy: "Laxmi Devi", uploadedAt: "2026-07-09", downloads: 0 },
        { id: 4, title: "NEB Grade 12 Physics Model Set 2082", type: "model-set", grade: "12", subject: "Physics", year: "2082", examType: "NEB", description: "Model question set for NEB Grade 12 Physics examination.", uploadedBy: "Laxmi Devi", uploadedAt: "2026-07-08", downloads: 0 },
        { id: 5, title: "NEB Grade 11 Chemistry Notes - Chemical Bonding", type: "notes", grade: "11", subject: "Chemistry", year: "2082", examType: "NEB", description: "Concise revision notes on chemical bonding for Grade 11 Chemistry.", uploadedBy: "Laxmi Devi", uploadedAt: "2026-07-07", downloads: 0 },
        { id: 6, title: "SEE Science Model Question Set 2081", type: "model-set", grade: "10", subject: "Science & Technology", year: "2081", examType: "SEE", description: "Model question set for SEE Science & Technology preparation.", uploadedBy: "Laxmi Devi", uploadedAt: "2026-07-05", downloads: 0 },
        { id: 7, title: "Grade 9 Compulsory Mathematics Question Paper (First Term 2082)", type: "question-paper", grade: "9", subject: "Compulsory Mathematics", year: "2082", examType: "First Term", description: "First terminal examination question paper for Grade 9 Mathematics.", uploadedBy: "Laxmi Devi", uploadedAt: "2026-07-03", downloads: 0 },
        { id: 8, title: "NEB Grade 12 English Model Set 2081", type: "model-set", grade: "12", subject: "Compulsory English", year: "2081", examType: "NEB", description: "Model question set for NEB Grade 12 Compulsory English.", uploadedBy: "Laxmi Devi", uploadedAt: "2026-07-02", downloads: 0 },
        { id: 9, title: "SEE Social Studies Question Paper 2080", type: "question-paper", grade: "10", subject: "Social Studies", year: "2080", examType: "SEE", description: "Previous year SEE Social Studies question paper 2080.", uploadedBy: "Laxmi Devi", uploadedAt: "2026-07-01", downloads: 0 },
        { id: 10, title: "Grade 8 Science & Technology Notes - Force and Motion", type: "notes", grade: "8", subject: "Science & Technology", year: "2082", examType: "BLE", description: "Revision notes on force and motion for Grade 8 Science & Technology.", uploadedBy: "Laxmi Devi", uploadedAt: "2026-06-28", downloads: 0 },
        { id: 11, title: "NEB Grade 11 Compulsory Mathematics Model Set 2082", type: "model-set", grade: "11", subject: "Compulsory Mathematics", year: "2082", examType: "NEB", description: "Model question set for NEB Grade 11 Compulsory Mathematics.", uploadedBy: "Laxmi Devi", uploadedAt: "2026-06-25", downloads: 0 },
        { id: 12, title: "SEE Compulsory Nepali Question Paper 2081", type: "question-paper", grade: "10", subject: "Compulsory Nepali", year: "2081", examType: "SEE", description: "Previous year SEE Compulsory Nepali question paper 2081.", uploadedBy: "Laxmi Devi", uploadedAt: "2026-06-22", downloads: 0 }
    ],

    cdcBooks: [],

    cdcGrades: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
    cdcSubjects: ["Nepali", "English", "Mathematics", "Social Studies", "Science", "Health", "Science & Technology", "Compulsory Mathematics", "Optional Mathematics", "Optional English", "Computer Science", "Economics", "Health Population & Environment", "Accountancy", "Physics", "Chemistry", "Biology", "Business Studies"]
};
